name       : erlang
version    : 21.0.6
release    : 30
source     :
    - https://github.com/erlang/otp/archive/OTP-21.0.6.tar.gz : a7da6ad97106b5ba087394658d41174ac1123d1f017bce02fbb9e43b49676f40
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(glu)
    - perl
    - wxwidgets-devel
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
