name       : erlang
version    : 21.2.2
release    : 32
source     :
    - https://github.com/erlang/otp/archive/OTP-21.2.2.tar.gz : 41b1c3a8343218157a683776e71d80a05ac4eb4019a90a760846608d78817690
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(glu)
    - perl
    - wxwidgets-devel
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
