name       : erlang
version    : 18.3.3
release    : 10
source     :
    - https://github.com/erlang/otp/archive/OTP-18.3.3.tar.gz : 70d50dd5970379cf0cd818bc5e21a1a809b9976c9ddd3a3b8ebde1e1c95ab8c3
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - flex-devel
    - perl
    - sed
setup      : |
    ./otp_build setup
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
