name       : erlang
version    : 23.0.2
release    : 36
source     :
    - https://github.com/erlang/otp/archive/OTP-23.0.2.tar.gz : 6bab92d1a1b20cc319cd845c23db3611cc99f8c99a610d117578262e3c108af3
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(x11)
    - perl
    - wxwidgets-devel
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
