name       : erlang
version    : 18.3.4
release    : 11
source     :
    - https://github.com/erlang/otp/archive/OTP-18.3.4.tar.gz : d9e68a8cdef4db0935b02d4b163cf3af403405f756488874736298cf48b90ae9
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - flex-devel
    - perl
    - sed
setup      : |
    ./otp_build setup
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
