name       : erlang
version    : 20.0
release    : 23
source     :
    - https://github.com/erlang/otp/archive/OTP-20.0.tar.gz : 548815fe08f5b661d38334ffa480e9e0614db5c505da7cb0dc260e729697f2ab
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - perl
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
