name       : erlang
version    : 18.2.4
release    : 6
source     :
    - https://github.com/erlang/otp/archive/OTP-18.2.4.tar.gz : 1c9ebe225a9223d428b653b038c75f15c19a239e1100db03eb8d105f1927a54d
license    : Apache-2.0
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - flex-devel
    - perl
    - sed
setup      : |
    ./otp_build setup
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
