name       : erlang
version    : 18.2.3
release    : 5
source     :
    - https://github.com/erlang/otp/archive/OTP-18.2.3.tar.gz : afb2d7dd8671623044c2b6baaf980c3c21dec7159f0367ffa7e66303197fbf7b
license    : Apache-2.0
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - flex-devel
    - perl
    - sed
setup      : |
    ./otp_build setup
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
