name       : erlang
version    : 24.0.5
release    : 40
source     :
    - https://github.com/erlang/otp/releases/download/OTP-24.0.5/otp_src_24.0.5.tar.gz : a5fec674b11d0a2b888963157a9de60fc384be27ff1a2175cd20708a5b9aa97d
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(odbc)
    - pkgconfig(x11)
    - perl
    - wxwidgets-devel
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
