name       : erlang
version    : 20.0.1
release    : 24
source     :
    - https://github.com/erlang/otp/archive/OTP-20.0.1.tar.gz : 8b121b38102acd43f89afd786055461741522c3a13ee17ef1a795c0dbf6aa281
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - perl
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
