name       : erlang
version    : 18.3.4.1
release    : 12
source     :
    - https://github.com/erlang/otp/archive/OTP-18.3.4.1.tar.gz : 3b9852083f3e5cf0668757af76833547233b8e67f4c28b51a6f49d4625bb23de
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - flex-devel
    - perl
    - sed
setup      : |
    ./otp_build setup
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
