name       : erlang
version    : 23.3.4.3
release    : 37
source     :
    - https://github.com/erlang/otp/releases/download/OTP-23.3.4.3/otp_src_23.3.4.3.tar.gz : 3040d0ce8f36212b01ba8ae19e49c510e7f5a2d1f5c3cec3c465dd20eb642e2a
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(x11)
    - perl
    - wxwidgets-devel
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
